## Configuration

baseURL = "http://example.org/"
languageCode = "en-us"
title = "Datadog Test"
theme = "mytheme"
relativeURLS = true

custom_css = ["css/main.css"]
custom_js = ["js/custom.js"]

[menu]
  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"

  [[menu.main]]
    identifier = "posts"
    name = "Posts"
    url = "/posts/"