## Configuration

baseURL = "http://example.org/"
languageCode = "en-us"
title = "Datadog Test"
theme = "mytheme"
relativeURLS = true
scss = ["scss/main.scss"]
custom_js = ["js/custom.js"]

[menu]
  [[menu.main]]
    identifier = "product"
    name = "Product"
    url = "/product/"

  [[menu.main]]
    identifier = "docs"
    name = "Docs"
    url = "/docs/"

  [[menu.main]]
    identifier = "pricing"
    name = "Pricing"
    url = "/pricing/"

  [[menu.main]]
    identifier = "customers"
    name = "Customers"
    url = "/customers/"

  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"

  [[menu.main]]
    identifier = "blog"
    name = "Blog"
    url = "/blog/"
